### ISSUE TITLE
Tree

### ISSUE THREAD

**Issue by jumi-shim** [Tech-Interview-A/Tech-Interview-Quetions#10]
트리의 개념
트리의 구성 요소
트리와 그래프의 차이점

**Comment by gaeunpark924** [comment]
> **트리의 개념**
> 
- 비선형이고 계층적 관계를 표현하는 자료구조
- Node(노드)와 Edge(간선)로 이루어져 있음
- **종류**
    1. 이진 트리 : 노드가 최대 2개의 자식을 갖는 트리
    2. 완전 이진 트리 : 노드가 왼쪽으로 졍렬된 트리
    3. 전 이진 트리 : 모든 노드가 0개 또는 2개의 자식 노드를 갖는 트리 
- **트리 순회(Tree Traversal)**
    1. 전위 순회(pre-order)
        1. 루트 노드를 처음 방문하는 방식
        2. 루트 - 왼쪽 자식 - 오른쪽 자식 순으로 순회
        3. 트리를 복사할 때 주로 사용됨(트리를 생성할 때 자식 노드모다 부모 노드가 먼저 생성되어야 하기 때문에)
    2. 중위 순회(in-order)
        1. 루트 노드를 중간에 방문하는 방식
        2. 왼쪽 자식 - 루트 - 오른쪽 자식 순으로 순회
        3. 이진 탐색트리(BST)에서 오름차순 또는 내림차순으로 값을 가져올 때 사용(내림차순으로 값을 가져오기 위해서는 역순(오른쪽 → root → 왼쪽)으로 중위 순회를 하면됨)
    3. 후위 순회(post-order)
        1. 루트 노드를 마지막에 방문하는 방식
        2. 왼쪽 자식 - 오른쪽 자식 순으로 순회
        3. 트리 삭제에 사용됨(부모노드를 삭제하기 전에 자식 노드를 삭제하는 순으로 노드를 삭제해야 하기 때문)
- **BST(Binary Search Tree, 이진 탐색 트리)**
    - 이진 트리이면서 아래와 같은 속성을 갖는 트리를 뜻한다.
        1. 이진 탐색 트리의 노드에 저장된 키(key)는 유일하다
        2. 부모의 키가 왼쪽 자식 노드의 키보다 크다.
        3. 부모의 키가 오른쪽 자식 노드의 키보다 작다.
        4. 왼쪽과 오른쪽 서브 트리도 이진 탐색 트리이다.

> **트리의 구성 요소**
> 
- Root Node(루트 노드): 부모가 없는 노드, 트리는 하나의 루트 노드를 가짐
- Terminal Node( = Leaf Node, 단말 노드): 자식이 없는 노드
- Internal Node(내부노드, 비단말 노드): 단말 노드를 제외한 모든 노드로 루트 노드를 포함

> **트리와 그래프의 차이점**
> 
- 트리는 일종의 DAG(Directed Acyclick Graphs, 방향성이 있는 그래프)
- 그래프와 가장 큰 차이점은 사이클 유무임
    - 사이클 불가능
    - 자체 간선(self-loop) 불가능
