### ISSUE TITLE
TCP & UDP

### ISSUE THREAD

**Issue by Kinaan-Oh** [Tech-Interview-A/Tech-Interview-Quetions#2]
- UDP 란?
- TCP 란?
- TCP 와 UDP의 차이점 ?

**Comment by Kinaan-Oh** [comment]
1.  TCP
- 신뢰적(loss X, in-order O), 연결지향 서비스(3-way handshake)
- 흐름제어 : 수신자 TCP 버퍼 오버플로 방지
- 혼잡제어(종단간) : 네트워크 혼잡에 따른 라우버 버퍼 오버플로에 인한 손실 방지. 네트워크 혼잡 원인(높은 전송률로 데이터를 전송하려는 너무나 많은 출발지)을 다룸.
- 연결 설정(3-way handshake)
클라이언트는 SYN 세그먼트(데이터 없음. SYN 비트 1)를 서버로 전송.
서버는 SYNACK 세그먼트(데이터 없음. SYN 비트 1)를 클라이언트로 전송.
클라이언트는 TCP 연결에 버퍼, 변수 할당. 클라이언트는 서버로 세그먼트(데이터 포함. SYN 비트 0) 전송.
- 연결 해제(4-way handshake)
클라이언트는 종료 세그먼트(FIN 비트 1)를 서버로 전송.
서버는 확인 세그먼트(ACK)를 클라이언트로 전송.
서버는 종료 세그먼트(FIN 비트 1)를 클라이언트로 전송.
클라이언트는 확인 세그먼트(ACK)를 서버로 전송.
예) SMTP(전자메일), Telnet(원격 터미널 접속), HTTP(웹), FTP(파일 전송)

2.  UDP
- 비신뢰적(loss O, in-order X), 비연결형 서비스
예) SNMP(네트워크 관리), RIP(라우팅 프로토콜), DNS(이름 변환)

3. TCP VS UDP
- UDP는 데이터를 UDP 세그먼트로 만들고, 즉시 그 세그먼트를 네트워크 계층으로 전달한다. TCP는 혼잡제어 메커니즘을 갖고 있다.
- UDP는 연결을 설정하기 위한 어떤 지연도 없다. TCP는 데이터 전송을 시작하기 전에 3-way handshake를 사용한다.
- UDP는 연결 상태가 없다. TCP보다 많은 클라이언트를 수용할 수 있다. TCP는 연결 상태를 유지한다. 연결 상태는 수신버퍼, 송신버퍼, 혼잡제어 파라미터, 순서번호, 확인응답번호 를 포함한다.
-  UDP는 단지 8바이트 헤더 오버헤드를 갖는다. TCP는 20바이트 헤더 오버헤드를 갖는다.

**Comment by gaeunpark924** [comment]
### TCP란?

- TCP는 신뢰성 있는 연결지향형 프로토콜
- 송신자과 수신자가 연결된 상태에서 데이터를 주고받음

### UDP란?

- UDP는 신뢰성이 낮은 비연결형 프로토콜
- 데이터를 주고 받을 때 연결 절차를 거치지 않고 송신측에서 일방적으로 데이터를 송신함

### TCP와 UDP의 차이점?
- 두 가지 다 OSI 7계층 중 전송 계층에서 사용하는 프로토콜로 송신자와 수신자 사이에 데이터를 전달하기 위해 사용함
- TCP는 데이터 교환전 3-way handshake로 연결을 설정하고 4-way handshake 로 연결을 해제하는 작업을 거치기 때문에 신뢰성이 높지만 속도가 느림
- TCP 헤더에 Sequence 번호로 데이터의 전송 순서를 기록하기 때문에 데이터의 순서가 유지되며 누락된 데이터를 확인할 수 있음
- UDP는 별도의 연결 과정이 없어 TCP에 비해 속도가 빠르지만 신뢰성이 낮음
- UDP는 손상된 세그먼트를 재전송하지 않음
- TCP는 신뢰성과 순차적인 전달이 필요한 경우 사용하고 UDP는 DNS, 동영상 스트리밍과 같이 신뢰성보다 속도가 중요한 경우 사용함
- TCP는 멀티캐스팅이나 브로드캐스팅을 지원하지 않음

**Comment by Mangso** [comment]
### Transport Layer
---
- End Point 간 **`신뢰성`** 있는 데이터 **`전송`** 을 담당하는 계층.
- 신뢰성 : 데이터를 순차적, 안정적인 전달
- 전송 : 포트 번호에 해당하는 프로세스에 데이터를 전달
- 신뢰성 있는 데이터를 포트 번호에 해당하는 프로세스에 전달.
- Transport Layer 가 없다면 ??
    - 데이터의 순차 전송 원할하지 않음. 송신자가 123을 전달했는데 231이 올 수 도.
    - Flow (흐름 문제)
        - 원인 : 송신자가 수신자한테 데이터를 보내는데 문제는 수신자 쪽에서 처리하는 속도가 더딤. 그 수신자가 데이터를 처리할 수 있는데 한계가 있음. 그 한계를 넘을 때 데이터가 온다면 데이터가 누락이 되겠지??
        
    - Congestion(혼잡 문제)
        - 네트워크 내의 패킷 수가 넘치게 증가하지 않도록 방지하는 것.
    - 결과적으로 Transport Layer가 없다면 ?? 데이터의 손실 발생.

### TCP 란?
---
- Transmission Control Protocol
- 신뢰성 있는 데이터 통신을 가능하게 해주는 프로토콜.
- 특징 : Connection 연결 (3 way handshake) - 양방향 통신.
- 데이터 순차 전송 보장,
- **`Flow control 흐름제어`**
    - 데이터를 송신하는 곳과 수신하는 곳의 데이터 처리 속도를 조절하여 수신자의 버퍼 오버플로우를 방지하는 것.
    - 송신하는 곳에서 감당이 안되게 많은 데이터를 빠르게 보내 수신하는 곳에서 문제가 일어나는 것을 막는다.
- **`혼잡 제어`**
    - 네트워크 내의 패킷 수가 넘치게 증가하지 않도록 방지하는것
    - 정보의 소통량이 과다하면 패킷을 조금만 전송하여 혼잡 붕괴현상 일어나는 것을 막는다.
- Error Detection (오류 감지)
- 세그먼트 : 데이터 전송 단위
- 연결지향적 프로토콜
    - 클라이언트와 서버가 연결된 상태에서 데이터를 주고 받음
    - 3way handshaking
    - 4-way handshaking 을 통해 연결을 해제.
- SYN - ACK 순차전달
    - 전송 순서를 보장.
    - 각 바이트마다 번호를 부여
- **`신뢰성 있는 데이터 전달`**
- Flow Control
    - 데이터 처리 속도를 조절하여 수신자의 버퍼 오버플로우를 방지
        - 송신하는 곳에서 감당이 안되게 많은 데이터를 빠르게 보내 수신하는 곳에서 문제가 일어나는 것을 막는다.
        - 수신자가 `윈도우크기(Window Size)` 값을 통해 수신량을 정할 수 있다.
- Congestion Control
    - 네트워크 내의 패킷 수가 넘치게 증가하지 않도록 방지
- UDP 보다 느림
- 전송의 신뢰성을 보장하지만 매번 Connection(3-way handshake) 를 연결해서 시간 손실 발생
- 패킷을 조금만 손실해도 재전송.

### UDP 란?

- User Datagram Protocol
- 순차 전송 X, 흐름 제어X, 혼잡 제어 X
- 의미 있는 서버를 구축하기 위해서는 일일이 패킷을 관리해주어야함.
    - 데이터의 신뢰성은 없지만 전송 속도가 일반적으로 빠른 프로토콜
- 실시간 멀티미디어.
    - 실시간 트랜스포트 프로토콜 (RTP) : UDP 패킷의 단일 스트림으로 몇몇 실시간 데이터 스트림을 멀티플렉싱하는 것.
        - UDP 스트림은 단일 목적지 또는 다중 목적지들로 전송될 수 있다.
        - 전달, 지연, 손실 등에 대한 특별한 보장 X

### TCP 와 UDP의 차이점 ?

![Screen Shot 2022-10-10 at 10 09 32 PM](https://user-images.githubusercontent.com/21096675/194964711-ca323e6e-ae55-4a1b-b335-7ecbaf180b94.png)

**Comment by JunginO** [comment]
### TCP 란?
- 연결형 서비스로 가상 회선 방식을 제공
- 3-way handshaking과정을 통해 연결을 설정하고 4-way handshaking을 통해 해제
- 높은 신뢰성을 보장
### UDP란?
- 비연결형, 신뢰성 없는 전송 프로토콜 → 데이터의 처리가 TCP보다 빠르다
- 주로 실시간 방송과 온라인 게임에서 사용된다 ex) 네트워크 환경이 안 좋을때, 끊기는 현상
- 세그먼트가 손실될 수 있고, 순서가 뒤바뀔 수 있다.
- Handshaking이 없음

#### 공통점

- 포트 번호 이용하여 주소 지정
- Checksum 이용하여 데이터 오류 검사

#### 차이점

|                  | TCP       | UDP               |
| ---------------- | --------- | ----------------- |
| 연결 방식        | 연결      | 비연결            |
| 패킷 교환 방식   | 가상 회선 | 데이터그램        |
| 전송 순서        | 보장      | 바뀔 수 있음      |
| 수신 여부        | 확인      | 비확인            |
| 통신 방식        | 1:1       | 1:1 or 1:N or N:N |
| 신뢰성           | 높음      | 낮음              |
| 속도             | 느림      | 빠름              |
| 혼잡제어         | O         | X                 |
| 흐름제어         | O         | X                 |
| Streaming 서비스 | 불리      | 유리              |
