### ISSUE TITLE
Process & Thread

### ISSUE THREAD

**Issue by Kinaan-Oh** [Tech-Interview-A/Tech-Interview-Quetions#3]
- 프로세스란 ?
- 스레드란 ?
- 프로세스와 스레드의 차이점 ?

**Comment by Kinaan-Oh** [comment]
1.  프로세스
정의

수행 중인 프로그램
컴퓨터상의 수행 중인 프로그램의 인스턴스
처리기에 할당되어 수행될 수 있는 개체
 

PCB(Process Control Block) 구성 요소

식별자(pid)
상태
우선순위
프로그램 카운터(PC)
메모리 포인터
문맥 데이터(context data)
입출력 상태정보
 

PCB(Process Control Block) 주요 역할

수행 프로세스를 인터럽트한 후 나중에 그 인터럽트가 발생되지 않은 것처럼 프로세스 수행을 재개할 수 있도록 충분한 정보를 유지
다수의 프로세스를 지원하고 다중처리를 제공할 수 있게 해주는 도구
Context Switching
어떤 프로세스가 인터럽트 될 때, 프로그램 카운터 및 처리기 레지스터들의 현재 값이 해당 PCB의 적절한 필드에 저장되고, 그 프로세스의 상태가 블록 또는 준비 등과 같은 값으로 변경.
OS는 다른 프로세스 선택하여 수행 상태로 만들고 그 프로세스의 프로그램 카운터와 문맥 데이터를 처리기 레지스터로 적재하여 새로운 프로세스를 수행.
 

자원 소유권

프로그램, 데이터, 스택, 그리고 속성들의 집합.
주기억장치, 입출력 채널, 입출력 장치, 파일과 같은 자원들에 대한 제어, 소유권을 프로세스에게 할당.
프로세스들 간에 자원들에 대한 불필요한 간섭이 일어나는 것을 막기 위해 운영체제는 보호 기능을 수행.
 

스케줄링

프로세스가 다른 프로세스들과 번강아 가면서(interleave) 수행.
프로세스는 수행 상태(ready, running 등) 와 디스패칭(dispatching) 우선순위가 있음.
프로세스는 운영체제에 의해 스케줄되고 디스패치 되는 개체.
2.  스레드
각 스레드마다 별도 제어블록(스택 포인터, 프로그램 카운터, 우선순위, 상태)를 갖는다.

프로세스 내 모든 스레드들은 그 프로세스의 자원을 공유.

프로세스 내 모든 스레드들은 같은 주소 공간에 존재하고 동일한 데이터에 접근한다. 프로세스 내 한 스레드가 메모리에 있는 데이터 항목을 변경했을 경우, 다른 스레드도 그 데이터 항목에 접근하여 결과를 확인할 수 있다.

하나의 스레드가 읽기 권한을 갖고 파일을 개방하면, 같은 프로세스에 있는 다른 스레드들도 그 파일을 읽을 수 있다.

 

장점

새로운 프로세스 생성 시간보다 존재하는 프로세스 내에서 새로운 스레드 생성 시간이 짧다.
프로세스 종료 시간보다 스레드 종료 시간이 짧다.
자원을 공유하므로 자원 소모가 적다.
프로세스간 교환(Context Switch)보다 같은 프로세스 내 두 스레드 교환이 효율적.
프로세스간 통신보다 스레드 간 통신이 효율적.
프로세스간 통신은 보호/통신기법을 제공하기 위해 커널이 개입.
같은 프로세스 내 스레드들은 메모리/파일을 공유하기 때문에, 커널 호출없이 통신 가능.
 

단점

프로세스 내 모든 스레드는 주소 공간, 파일과 같은 자원을 공유하므로, 하나의 스레드에 의한 자원 변경은 같은 프로세스 내 다른 스레드에 영향을 미침. 따라서, 스레드들이 서로 간섭하지 않도록 동기화가 필요.

**Comment by gaeunpark924** [comment]
### 프로세스란?
- 실행 중인 프로그램의 인스턴스
- 하나의 프로세스는 여러 개의 쓰레드를 관리할 수 있고 최소 한 개의 쓰레드를 가짐
- 프로세스의 상태 정보는 PCB에 저장됨

### 쓰레드란?
- 프로세스 내부의 실행 단위
- 프로세스에 할당된 메모리, CPU 등의 자원을 사용함

### 프로세스와 스레드의 차이점
- 프로세스는 운영체제로부터 독립된 메모리 영역을 할당받지만 쓰레드는 같은 프로세스 내에서 heap, data, code 영역을 공유하고 stack 영역만 독립적으로 할당받는다.
- 따라서 같은 프로세스 내의 쓰레드들은 프로세스의 자원을 공유할 수 있다.
- 이와 같은 특징때문에 멀티 쓰레드 환경에서 동기화 문제가 발생할 수 있습니다.

**Comment by Mangso** [comment]
### 프로세스란 ?

- CPU에 의해 처리되는 User 프로그램 혹은 시스템 프로그램을 의미한다.
- **`컴퓨터에서 실행 중인 프로그램. 각각의 프로세스는 독립된 메모리 공간`** 을 할당 받음.
- 프로그램이 실행되기 위해서는 CPU로 부터 필요한 자원을 할당 받아야 하는데, 디스크로부터 메모리에 적재되어 CPU의 할당을 받을 수 있는 실행중인 프로그램을 프로세스라고 한다.
- **`명령에 의해 자원을 할당받아 실행되는 작업의 단위를 프로세스`** 라고 한다.
- 운영체제로부터 **`독립된 메모리 영역을 할당`**받는다.
- 프로세스들은 독립적이기 때문에 통신하기 위해 IPC를 사용해야 한다
- 프로세스는 최소 1개의 쓰레드(메인 쓰레드)를 가지고 있다.

### 스레드란 ?

- 쓰레드는 **`프로세스 내에서 실행되는 여러 실행 흐름의 단위`** 로써 프로세스의 특정한 수행 경로를 의미합니다.
- 쓰레드는 프로세스가 할당받은 자원을 이용해서 실행됨.
- 멀티 쓰레드일 경우에 각각의 쓰레드는 메모리 , stack 영역만 따로 할당받고 나머지 Code, Data, Heap 영역은 공유함.

### Q. 스택을 스레드마다 독립적으로 할당하는 이유?`**

A. 스택은 **`함수 호출 시 전달되는 인자, 되돌아갈 주소값 및 함수 내에서 선언하는 변수 등을 저장하기 위한 공간`** 입니다. 스택 메모리 공간이 독립적이라는 것은 독립적인 함수 호출이 가능하다는 의미이고, 이는 **`독립적인 실행 흐름이 추가 되는 것`** 을 의미합니다. 따라서 스레드의 정의에 따라 독립적인 실행 흐름을 추가하기 위한 최소 조건으로 독립된 스택을 할당합니다.

- 한 마디로 Stack을 공유하게 되면 LIFO 구조에 의해 실행 순서가 복잡해지기 때문에 실행흐름을 원활하게 만들기 위함.

### Q. PC Register를 스레드마다 독립적으로 할당하는 이유?

A. PC값은 스레드가 명령어의 어디까지 수행하였는지를 저장합니다. 스레드는 CPU를 할당받았다가 스케줄러에 의해 다시 선점 당하므로 명령어가 연속적으로 수행되지 못합니다. 따라서 어느 부분까지 수행되었는지 기억할 필요가 있기 때문에 PC Register를 독립적으로 할당합니다.

**Comment by JunginO** [comment]
### 프로세스란 ?
- 컴퓨터에서 연속적으로 실행되고 있는 컴퓨터 프로그램
- 메모리에 올라와 실행되고 있는 프로그램의 인스턴스(독립적인 개체)
### 스레드란 ?
- 프로세스 내에서 실행되는 여러 흐름의 단위
- 프로세스가 할당받은 자원을 이용하는 실행의 단위

### 프로세스와 스레드의 차이점 ?
- 프로세스는 운영체제로부터 자원을 할당받는 작업의 단위
- 스레드는 프로세스가 할당받은 자원을 이용하는 실행의 단위이며 프로세스 내에 여러개 생길 수 있다.

### 멀티프로세스와 멀티스레드
**멀티프로세스**
- 멀티프로세스는 하나의 프로그램을 여러개의 프로세스로 구성하여 각 프로세스가 하나의 작업을 처리하는 것

장점: 하나의 프로세스가 잘못되어도 프로그램 동작가능
단점: Context Switching 비용 발생

**멀티스레드**
- 멀티스레드는 프로그램을 여러개의 스레드로 구성하고 각 스레드가 작업을 처리하는것

장점: 시스템 자원 소모 감소, 처리 비용 감소(실행 속도 향상), 스레드간 자원 공유
단점: 디버깅 어려움, 동기화 이슈 발생, 하나의 스레드 오류로 전체 프로세스 문제 발생
