### ISSUE TITLE
HashTable

### ISSUE THREAD

**Issue by Mangso** [Tech-Interview-A/Tech-Interview-Quetions#4]
* HashTable 이란?
* HahsTable의 동작 과정
* Hash Function 이란?
* Conflict를 해결하는 방법?

**Comment by Kinaan-Oh** [comment]
사전은 쌍의 집합으로 각 쌍은 키와 이에 관련된 원소로 구성된다. 해싱은 사전 연산인 Get, Insert, Delete를 Time Complexity O(1)에 수행할 수 있는 기법이다.

 1.  정적 해싱

 정적 해싱에서는 사전 쌍들이 해시 테이블(hash table)이라는 ht 테이블에 저장된다. 헤시 테이블은 ht[0], ..., ht[b-1]과 같이 b개의 버킷(bucket)으로 분할된다. 각 버킷은 s개의 사전 쌍들을 포함한다. 한 버킷은 s개의 슬롯(slot)으로 구성되며 한 슬롯에는 하나의 사전 쌍을 저장할 수 있다. 키 값이 k인 한 쌍의 주소 또는 위치는 해시 함수(hash function) h에 의해 결정되는데 이 해시 함수는 키 값을 버킷으로 사상시킨다. 즉, 어떤 키 값 k에 대해서 h(k)는 0과 b-1 사이의 정수가 된다. h(k)를 해시 또는 홈 주소라고 한다.

2.  해시 함수

 해시 함수는 키를 해시 테이블 내의 버킷으로 사상시킨다. 해시 함수는 계산이 쉽고, 충돌이 적어야 한다. 즉, k가 키 고간에서 임의로 선택된 키라면 h(k) = i가 될 확률은 모든 버킷 i에 대해 1/b가 되면 좋다. 이런 해시 함수를 균일 해시 함수(uniform hash function)라 한다. 가장 많이 쓰는 해시 함수는 제산 함수(division)으로서 홈 버킷은 mod(%) 연산자에 의해 결정된다. 즉, 키 k를 어떤 정해진 수 D로 나눈 나머지를 k의 홈 버킷으로 사용한다. h(k) = k % D. 여기서 D의 선택이 오버플로 발생 수에 큰 영향을 미친다. D가 2로 나누어지는 값이면 홀수 값을 가진 키들은 홀수 버킷으로 사상될 것이다. 또한 짝수 값을 가진 키들은 짝수 버킷으로 사상될 것이다. 즉, D를 짝수로 한다면 홈 버킷들이 어느 한쪽으로만 편중될 것이다. D가 2, 3, 5, 7 등과 같이 작은 소인수를 약수로 가질 때 홈 버킷들이 한쪽으로 편중된다는 것이 관찰되었다. 따라서 최상의 성능을 내기 위해서는 소수인 D를 선택해야 한다.

3.  오버플로 처리

3-1.  개방 주소법(Open Addressing)

 선형 조사법(linear probing), 이차 조사법(quadratic probing), 재해싱(rehashing), 임의 조사법(random probing) 등의 방법이 있다. 선형 조사법은 키 값이 k인 새로운 쌍 하나를 삽입할 때 ht[(ht(k)+i)%b] (i>=0) 의 순서에 따라 해시 테이블 버킷을 검색한다. 다 채워지지 않은 버킷을 만나면 검색이 끝나고 새로운 쌍이 그 버킷으로 삽입된다. 빈 자리가 있는 버킷이 없다면 해시 테이블이 만원이라는 뜻이므로 테이블 크기를 늘려야 한다. 해시 테이블 크기를 다시 정할 때 해시 함수 역시 바꿔야 한다. 제수를 버킷의 수와 동일하게 바꿔야 한다.

3-2.  체인법(Chaining)

 선형 조사법의 효율이 좋지 않은 이유는 키를 탐색할 때 서로 다른 해시 값을 가진 키와 비교를 해야 하기 때문이다. 만약 각 버킷에 대해 그 버킷에 대한 동거자들을 키 리스트로 구성한다면, 위와 같은 불필요한 비교들은 하지 않아도 될 것이다. 일반적으로 체인법과 함께 제산 함수를 사용하면 가장 좋은 성능을 갖게 된다.

 성공적인 탐색을 위해 필요한 최악의 경우의 비교 횟수는 개방 주소법, 체인법 모두 O(n)이다. 최악의 경우 비교 횟수는 만일 동거자를 체인이 아니라 균형 탐색 트리로 저장한다면 O(lgn)으로 줄일 수 있다.

4.  동적 해싱

 좋은 성능을 보장하기 위해서는 적재 밀도가 경계 값을 넘을 때마다 해시 테이블의 크기를 증가시켜야 한다. 해시 테이블에 버킷 b개가 있다고 할 때, 버킷의 수를 2b+1로 늘리고 제수도 2b+1로 변경해야 한다. 변경 후 원래 해시 테이블에서 모든 사전 쌍들을 큰 해시 테이블로 다시 삽입해야 한다. 이 재조정은 비용이 크다. 동적 해싱은 재종을 한 번 할 때마다 오직 하나의 버킷 안에 있는 엔트리에 대해서만 홈 버킷을 변경하게 하여 재조정 시간을 줄이는 방법이다. 대표적으로 디렉터리를 이용하는 방법이 있다.

**Comment by gaeunpark924** [comment]
### HashTable 이란?

- 키(Key) 1개와 값(Value) 1개가 1:1로 연관되어 있는 자료구조
- Key 값에 해시함수를 적용해서 실제 값이 저장되는 장소의 index로 사용함
- index로 값을 한 번에 찾을 수 있기 때문에 삽입/탐색 연산의 평균 시간복잡도는 O(1)이다.
- 충돌이 발생하면 연결된 리스트들까지 탐색해야 하기 때문에 시간복잡도는 O(n)으로 늘어난다.
- 실제 값이 저장되는 장소를 버킷이라고 한다.

### HahsTable의 동작 과정

Key가 “Apple”이고 Value가 1500원인 데이터를 해시 테이블에 저장한다. (버킷 사이즈: 10)

1. 해시 함수를 이용해 “Apple”을 해시값으로 변환하고 10으로 나눈 나머지를 계산한다.
2. 나머지를 배열의 index로 해서 1500원 가격을 저장한다. 
3. 해시값이 중복되면 연결리스트로 중복되는 값을 연결한다.
- 데이터를 찾을 때는 해시 함수를 1번만 수행하면 된다
- 연결리스트가 한 번 안에 끝나면 O(1)이고 운이 나빠서 연결리스트가 한쪽에 전부 걸리면 O(n)이다
- rehashing : 버킷 사이즈에 들어가는 element가 일정 수준이 넘어가면 해시맵을 새로 그린다

### Hash Function 이란?

- 임의 길이의 값을 고정된 크기의 값으로 변환해주는 함수
- 해시값을 색인(index)으로 만들기 위해 사용함

### Conflict를 해결하는 방법?

1. Chaining
- 충돌이 발생하면 연결리스트로 저장

<img src="https://user-images.githubusercontent.com/51811995/195483257-8e784bb6-e931-4f45-9dff-3e79063b28b2.png" width=500>


2. Open Addressing
- 동일한 주소에 다른 데이터가 있을 경우 다른 주소도 이용할 수 있게 하는 기법

1. 삽입 : 계산한 해시 값에 대한 인덱스가 이미 차있는 경우 다음 인덱스로 이동하면서 비어있는 곳에 저장한다. 비어있는 자리를 탐색하는 것을 탐사(Probing)라고 한다.
2. 탐색 : 계산한 해시 값에 대한 인덱스부터 검사하며 탐사를 해나가는데 “삭제” 표시가 있는 부분은 지나간다.
3. 삭제 : 탐색을 통해 해당 값을 찾고 삭제한 뒤 “삭제” 표시를한다.

< Open Addressing의 3가지 충돌 처리기법 >

1. 선형탐사(Linear Probing)
- 인접한 인덱스에 데이터를 탐색하는 방식
- 클러스터링 문제가 발생하고 탐색과 삭제가 느려짐

2. 제곱탐사(Quadratic Probing)
- 인덱스를 제곱수로 탐사하는 방식
- 선형탐사보다 폭넓게 탐사하여 탐색과 삭제에 효율적임
- 초기 해시값이 같으면 클러스터링 문제가 발생

3. 이중해싱(Double Hashing)
- 선형탐사와 제곱탐사의 클러스터링 문제를 피하기 위해 도입
- 해시함수를 2개 사용하는데 하나는 해시값을 찾기 위해 사용하고 다른 하나는 충돌 발생했을 때 탐사폭을 계산하기 위해 사용한다.

**Comment by dlgosla** [comment]
- HashTable 이란?
    - 해싱을 통해 값을 저장하는 자료구조
- HahsTable의 동작 과정
    - key값을 해시 함수를 거쳐서 나온 해시값을 index로 사용해서 그 위치에 데이터를 저장
- Hash Function 이란?
    - 임의의 길이의 데이터를 고정된 길이의 데이터로 매핑
- Conflict를 해결하는 방법?
    - 개방 주소법
        - 충돌이 발생하면 다른 인덱스에 저장
        - 캐시 효율이 좋다, 메모리 효율이 좋다
        - 테이블 확장이 필요하다
        
        - 선형 탐사
            - 일정한 길이만큼 이동해가면서 빈 곳에 저장
            - 캐시 효율이 좋다
            - 데이터가 특정 위치에 밀집되는 1차 클러스터링 문제 → 성능 하락
            
        - 제곱 탐사
            - 제곱 길이만큼 이동해 가면서 빈 곳에 저장
            - 1→ 2^2 → 3^2
            - 두 키가 처음 같은 곳에서 충돌이 발생하면 계속 충돌이 발생하는 2차 클러스터링 문제
            - 선형 탐사에 비해 폭넓은 탐색
        
        - 이중 해싱
            - 2차 해시 함수를 사용해서 다른 주소에 저장
            - 클러스터링 문제에 영향 거의 안받음
            - 연산량 많다
    
    - 분리 연결법
        - 트리, 연결 리스트 같은 자료구조를 버킷에 연결해서 다음 데이터를 저장하는 방식
        - 캐시의 효율이 나쁘다, 메모리를 많이 잡아먹는다.
        - 해시테이블 확장을 줄일 수 있다
        - 트리
            - rb 트리 - log(n) 삽입,삭제, 조회 보장
            - 메모리 사용 증가 - 데이터 많을 때 사용하는 게 좋음
        - 링크드 리스트
            - 최악의 경우 O(n)의 탐색 속도
            - 간단한 구현

**Comment by Mangso** [comment]
## **1. 해시테이블이란?**

- Key - Value가 하나의 쌍을 이루는 데이터 구조.
- key와 배열의 index를 이용하여 키를 저장하는 자료 구조.
- Hash Map, Map, Dictionary, 연관 배열 등 이름으로 알려짐
- index = hash_function("Lisa Smith") % 16 -> buckets[index] = "521-8976" 저장
- 해시테이블 평균 저장 / 삭제 / 조회 시간복잡도 O(1)
- Key와 Value를 1:1로 연관지어 저장하는 자료구조 (연관배열 구조)
- Key를 이용하여 Value 도출

## **2. 해시 함수**

- 해시 함수 (Hash function)는 임의의 길이의 키값을 **`고정된 길이의 해시로`** 변환해주는 맵핑 함수입니다.
- 데이터를 효율적으로 관리하기 위해 임의의 길이의 데이터를 고정된 길이의 데이터로 매핑하는 함수

### **1. Division Method 나눗셈**

- buckets 수만큼 나눗셈 나머지, 그 나머지를 테이블의 주소로 사용
- 어떤 값이든 테이블 크기로 나누면 그 나머지는 절대 테이블 크기를 넘지 않음
- 테이블의 크기 n을 소수로 정하는 것이 좋다
- 크기를 n이라 할 때 0 ~ n-1 사이의 주소를 반환함을 보장

### **2. Digit Folding 자릿수 접기**

- 숫자의 각 자릿수를 더해 해시값을 만드는 것
- ex) 583924를 각각 자릿수별로 더하면 31 -> 이제 두 자리씩 Folding -> 121

## **3. 해시 충돌 해결**

> John Smith 와 Sandra Dee의 해시값이 같다면?
> 

해시란 데이터를 다루는 기법 중에 하나로 **검색과 저장이 아주 빠르게**
 진행됩니다

- Hash 충돌
    - 서로 다른 Key가 Hash Function에서 중복 Hash로 나오는 경우
    - 충돌이 많아질수록 탐색의 시간 복잡도가 O(1)에서 O(n)으로 증가

### **1. Separate Chaining - 분리 연결법**

- Linked List(데이터 6개 이하) 또는 Red-Black Tree(데이터 8개 이상) 사용

![https://github.com/workhardslave/cs-study/raw/main/Data%20Structure/img/hash2.png](https://github.com/workhardslave/cs-study/raw/main/Data%20Structure/img/hash2.png)

- 동일한 버킷의 데이터에 대해 자료구조를 활용해 추가 메모리를 사용하여 다음 데이터의 주소를 저장하는 것
    - **연결 리스트를 사용하는 방식(Linked List)** 각각의 버킷(bucket)들을 연결리스트(Linked List)로 만들어 Collision 이 발생하면 해당 bucket 의 list 에 추가하는 방식이다. 연결 리스트의 특징을 그대로 이어받아 삭제 또는 삽입이 간단하다. 하지만 단점도 그대로 물려받아 작은 데이터들을 저장할 때 연결 리스트 자체의 오버헤드가 부담이 된다. 또 다른 특징으로는, 버킷을 계속해서 사용하는 Open Address 방식에 비해 테이블의 확장을 늦출 수 있다.
    - **Tree 를 사용하는 방식 (Red-Black Tree)** 기본적인 알고리즘은 Separate Chaining 방식과 동일하며 연결 리스트 대신 트리를 사용하는 방식이다. 연결 리스트를 사용할 것인가와 트리를 사용할 것인가에 대한 기준은 하나의 해시 버킷에 할당된 key-value 쌍의 개수이다. 데이터의 개수가 적다면 링크드 리스트를 사용하는 것이 맞다. 트리는 기본적으로 메모리 사용량이 많기 때문이다. 데이터 개수가 적을 때 Worst Case 를 살펴보면 트리와 링크드 리스트의 성능 상 차이가 거의 없다. 따라서 메모리 측면을 봤을 때 데이터 개수가 적을 때는 링크드 리스트를 사용한다.
- Java8의 Hash 테이블은 Self-Balancing Binary Search Tree 자료구조로 Chaining 방식 구현
- 테이블 확장이 필요 없고, 간단하게 구현 가능.
- 손쉽게 삭제 가능
- 동일한 버킷에 chaining 되는 데이터가 많아져서 캐시 효율성 감소한다는 단점

### **2. Open Addressing - 개방 주소법**

- 추가적인 메모리를 사용하는 Chaining 방식과 다르게 비어있는 해시 테이블의 공간 활용
- Linear Probing : 현재 버킷 index로부터 고정폭 만큼씩 이동하여 차례대로 검색해 비어있는 버킷에 저장
- Quadratic Probing : 해시의 저장 순서 폭을 제곱으로 저장하는 방식
- Double Hashing 해시된 값을 한번 더 해싱

![https://github.com/workhardslave/cs-study/raw/main/Data%20Structure/img/hash3.png](https://github.com/workhardslave/cs-study/raw/main/Data%20Structure/img/hash3.png)

1. Resizing
    - 저장 공간이 일정 수준 채워지면 Separating Chaining의 경우 성능 향을 위해, Open addressing의 경우 배열 크기 확장을 위해 Resizing
    - 보통 두배로 확장
    - 확장 임계점은 현재 데이터 개수가 Hash Bucket 개수의 75%가 될 때

### **`Open Address` vs `Separate Chaining`**

일단 두 방식 모두 Worst Case 에서 O(M)이다. 하지만 `Open Address`방식은 연속된 공간에 데이터를 저장하기 때문에 `Separate Chaining`에 비해 캐시 효율이 높다. 따라서 데이터의 개수가 충분히 적다면 `Open Address`방식이 `Separate Chaining`보다 더 성능이 좋다. 한 가지 차이점이 더 존재한다. `Separate Chaining`방식에 비해 `Open Address`방식은 버킷을 계속해서 사용한다. 따라서 `Separate Chaining` 방식은 테이블의 확장을 보다 늦출 수 있다.

### **보조 해시 함수**

보조 해시 함수(supplement hash function)의 목적은 `key`의 해시 값을 변형하여 해시 충돌 가능성을 줄이는 것이다. `Separate Chaining` 방식을 사용할 때 함께 사용되며 보조 해시 함수로 Worst Case 에 가까워지는 경우를 줄일 수 있다

# 해시 테이블 동작 과정

- 특정 데이터가 저장되는 인덱스는 그 데이터만의 고유한 위치이기 때문에, 삽입 연산 시 다른 데이터의 사이에 끼어들거나, 삭제 시 다른 데이터로 채울 필요가 없으므로 연산에서 추가적인 비용이 없도록 만들어진 구조이다.
- **특별한 알고리즘을 이용하여** 저장할 데이터와 연관된 **고유한 숫자를 만들어 낸 뒤** 이를 인덱스로 사용한다.
- Key -> Hash Function -> Hash Function 결과 = Hash
- Hash를 배열의 Index로 사용해당 Index에 Value 저장
- HashTable 크기가 10이라면 A라는 Key의 Value를 찾을 때 hashFunction("A") % 10 연산을 통해 인덱스 값 계산하여 Value 조회

### HashTable 장점

- 적은 리소스로 많은 데이터를 효율적으로 관리 가능
    - ex. HDD. Cloud에 있는 많은 데이터를 Hash로 매핑하여 작은 크기의 시 메모리로 프로세스 관리 가능
- 배열의 인덱스를 사용하기 때문에 빠른 검색, 삽입, 삭제 (O(1))
    - HashTable의 경우 인덱스는 데이터의 고유 위치이기 때문에 삽입 삭제 시 다른 데이터를 이동할 필요가 없어 삽입, 삭제도 빠른 속도 가능
- Key와 Hash에 연관성이 없어 보안 유리
- 데이터 캐싱에 많이 사용
    - get, put 기능에 캐시 로직 추가 시 자주 hit하는 데이터 바로 검색 가능
- 중복 제거 유용

### HashTable 단점

- 충돌 발생 가능성
- 공간 복잡도 증가
- 순서 무시
- 해시 함수에 의존

**Comment by jumi-shim** [comment]
내부적으로 배열을 사용해 데이터 저장. 해시 알고리즘을 이용해 고유한 인덱스를 얻고 이 인덱스를 이용하여 빠른 검색 속도를 갖음.

해시 : 다양한 길이를 가진 데이터를 고정된 길이의 데이터로 매핑한 값.

- 해시 함수
    
    데이터를 효율적으로 관리하기 위해 임의의 길이의 데이터를 수학적 연산을 통해 고정된 길이의 데이터로 매핑하는 함수. 해시 함수에 의해 얻어지는 값을 해시코드, 해시라고 함.
    
    해시함수를 무조건 1:1로 만드는 것보다 충돌을 최소화하고 충돌에 어떻게 대응할 것인가가 더 중요.
    

- 해시 충돌
    
    데이터가 많아지면 다른 데이터가 같은 해시 값을 가지게 되어 충돌이 발생하게 됨. 즉, 서로 다른 데이터가 동일한 해시 값을 가질 수 있어 해시 충돌 발생.
    
- 해시 충돌 해결 방법
    - separate chaining
        
        key에 대한 index가 가리키는 자료구조를 linked list를 이용하는 방식.
        
        보조 해시 함수를 통해 worst case 줄일 수 있음.
        
        index로 인해서 충돌이 발생하면 그 index가 가리키고 있는 linked list에 노드 추가.
        
        Tree이용하면 성능 개선 가능. (메모리 사용량이 많기 때문에 key-value 쌍 개수로 결정 가능. 데이터 개수가 적다면 list)
        
    - open addressing
        
        해시 충돌이 발생하면 해시 함수로 얻은 주소가 아닌 다른 주소 공간에 데이터를 저장하는 방식. (해당 키에 데이터가 저장되어 있으면 다음 주소에 저장)
        
        separate chaining보다 느림. 채운 밀도가 높아질 수록 worst case 많아짐.
        
        - 선형 탐사 : 고정 크기 만큼 다음 주소로 이동
        - 제곱 탐사 : 고정 크기 만큼 이동하는 것이 아닌 제곱수
        - 이중 해싱 : 해시 충돌 시 다른 해시 함수 적용.
        - 재해싱 : 해시 테이블 크기를 늘리고 늘어난 해시 테이블의 크기에 맞추어 모든 테이블 다시 해싱.
        
    - open address vs separate chaining
        
        open address 방식은 연속된 공간에 데이터를 저장하기 때문에 캐시 효율 높음. 따라서 데이터 개수가 충분히 적다면 open address가 좋음. 
        
        separate 방식은 테이블 확장을 늦출 수 있음.
        
- 장점
    
    적은 자원으로 많은 데이터를 효율적으로 관리하기 위함. 하드디스크나 클라우드에 존재하는 무한한 데이터들을 유한한 개수의 해시값으로 매핑하면 적은 메모리로도 프로세스 관리 가능.
    

- hash table vs hash map
    - hash map
        
        map 인터페이스를 구현하기 위해 hash table을 사용한 클래스로 key와 value에 null 허용. 동기화 지원 안 함.
        
    - hash table
        
        hash map 보다 속도는 느리지만 동기화 지원하고 key와 value에 Null 허용 안 함.
