### ISSUE TITLE
TCP/IP Protocol

### ISSUE THREAD

**Issue by Mangso** [Tech-Interview-A/Tech-Interview-Quetions#5]
* 4 계층에 대한 개념과 설명

**Comment by gaeunpark924** [comment]
**4계층: 응용계층(Application Layer)**

- 응용 프로그램에서 데이터를 처리하는 계층
- 사용자와 가장 가까운 계층으로 사용자-소프트웨어간 소통 담당함
- 특정 서비스를 제공하기 위해 애플리케이션끼리 정보를 주고 받는 것
- HTTP, FTP, SSH, Telnet, DNS, SMTP

**3계층: 전송계층(Transport Layer)**

- 포트 번호를 사용해 데이터를 목적지 기기 내 적절한 애플리케이션으로 전달
- 송신된 데이터를 수신측 애플리케이션에 확실히 전달하게 한다
- TCP, UDP, RTP, RTCP

**2계층: 인터넷 계층(Internet Layer)**

- IP 주소를 사용해 최종 목적지까지 라우팅하는 계층
- 네트워크상에서 최종 목적지까지 정확하게 찾아갈 수있도록 해준다
- IP, ARP

**1계층: 네트워크 계층(Network Access Layer)**

- 데이터를 전기신호로 변환하고 MAC 주소를 사용해 네트워크상에 직접 연결된 기기로 데이터를 전송함
- Eternet, Wi-Fi, PPP, Token Ring 과 같은 프로토콜 사용됨
- Frame, 브리지/스위치

**Comment by dlgosla** [comment]
tcp/ip

- tcp,ip를 중심으로 인터넷 통신을 위해 필요한 프로토콜들의 집합
- ip는 목적지 까지 패킷을 라우팅하고 tcp로 오류 없이 수신

- ip
    - 목적지 까지 빠르게 데이터를 전송하기 위한 프로토콜
    - 순서 보장 x, 패킷 전달 여부 x

- tcp
    - 두 노드 간의 신뢰도 높은 통신 제어를 위한 프로토콜
    - 순서 보장, 패킷 전달 여부

- 4계층
    1. 네트워크 액세스 계층
        1. mac 주소를 사용해 데이터를 전기 신호로 바꿔서 전달
    
    1. 인터넷 계층
        1. 패킷을 목적지 까지 라우팅
    
    1. 통신 계층
        1. 노드 간의 연결을 제어
    
    1. 어플리케이션 계층
        1. 사용자와 sw 간의 소통을 담당

**Comment by Mangso** [comment]
# Network

### **TCP/IP 프로토콜을 스택 4계층으로 짓고 설명하시오**

• **TCP/IP 4계층은, TCP/IP 프로토콜 통신 과정에 초점을 맞추어, OSI 7계층을 좀 더 단순화 시킨 계층을 의미합니다.**

- **이러한 계층적인 구조는 아래와 같은 특징을 가지고 있습니다.**
    - 각 계층별 처리 역할이 다르기 때문에, 계층별 간섭을 최소화할 수 있습니다.
    - 특정 계층에서 문제가 생기면, 해당 계층을 살펴보면 되기 때문에, 유지 보수가 편리합니다.
    - 다른 계층끼리는 데이터의 전달 과정을 구체적으로 알 필요가 없기 때문에, 데이터의 캡슐화와 은닉이 가능합니다.
    
- **LINK 계층**
    
    물리적인 영역의 표준화에 대한 결과
    
    가장 기본이 되는 영역으로 LAN, WAN과 같은 네트워크 표준과 관련된 프로토콜을 정의하는 영역이다
    
- **IP 계층**
    
    경로 검색을 해주는 계층임
    
    IP 자체는 비연결지향적이며, 신뢰할 수 없는 프로토콜이다
    
    데이터를 전송할 때마다 거쳐야할 경로를 선택해주지만, 경로가 일정하지 않음. 또한 데이터 전송 중에 경로상 문제가 발생할 때 데이터가 손실되거나 오류가 발생하는 문제가 발생할 수 있음. 따라서 IP 계층은 오류 발생에 대한 대비가 되어있지 않은 프로토콜임
    
- **TCP/UDP (전송) 계층**
    
    데이터의 실제 송수신을 담당함
    
    UDP는 TCP에 비해 상대적으로 간단하고, TCP는 신뢰성잇는 데이터 전송을 담당함
    
    TCP는 데이터 전송 시, IP 프로토콜이 기반임 (IP는 문제 해결에 문제가 있는데 TCP가 신뢰라고?)
    
    → IP의 문제를 해결해주는 것이 TCP인 것. 데이터의 순서가 올바르게 전송 갔는지 확인해주며 대화를 주고받는 방식임. 이처럼 확인 절차를 걸치며 신뢰성 없는 IP에 신뢰성을 부여한 프로토콜이 TCP이다
    
- **애플리케이션 계층**
    
    서버와 클라이언트를 만드는 과정에서 프로그램 성격에 따라 데이터 송수신에 대한 약속들이 정해지는데, 이것이 바로 애플리케이션 계층이다
    

# 4계층 : 애플리케이션 계층(Application Layer)

- **사용자와 가장 가까운 계층으로, 사용자-소프트웨어 간 소통을 담당하는 계층입니다.**
- 애플리케이션을 실행하기 위한 데이터 형식이 작성됩니다.
- **프로토콜로는 HTTP, HTTPS, FTP, SSH, Telnet, DNS, SMTP 가 있습니다.**

# **3계층 : 전송 계층(Transport Layer)**

- **통신 노드 간 신뢰성 있는 데이터 전송을 보장하는 계층입니다.**
- 역캡슐화 과정에서, 포트 번호를 사용해 데이터를 정확한 애플리케이션에 전달하는 역할도 합니다.
    - 네트워크 액세스 계층과 인터넷 계층을 통해, 데이터가 목적지 기기까지 정상적으로 도착했다면,
    - 전송 계층은 포트 번호를 사용해, 데이터를 목적지 기기 내 적절한 에플리케이션으로 전달합니다.
- **프로토콜로는 TCP, UDP, RTP, RTCP 가 있습니다.**

# 2계층 : 인터넷 계층(Internet Layer)

- **패킷을 최종 목적지까지 라우팅하는 계층입니다.**
- 프로토콜로는 IP, ARP, ICMP, RARP, OSPF 가 사용됩니다.

# 1계층 : 네트워크 액세스 계층(Network Access Layer or Network Interface Layer)

- **데이터를 전기신호로 변환한 뒤, 물리적 주소인 MAC 주소를 사용해, 알맞은 기기로 데이터를 전달하는 계층입니다.**
- 프로토콜로는 Ethernet, Wi-Fi, PPP, Token Ring 과 같은 프로토콜이 사용됩니다.

![Untitled](https://user-images.githubusercontent.com/21096675/195597474-450c569d-ee7d-4141-8905-2387bcfc74da.png)


- IP 계층에서 오류 나면 복구를 하는지?
- MAC 주소가 뭔지 설명?
    - 컴퓨터 하드웨어 주소.
- 어플리케이션에서 사용하는 예?
