### ISSUE TITLE
Context Switching & DeadLock

### ISSUE THREAD

**Issue by Mangso** [Tech-Interview-A/Tech-Interview-Quetions#6]
* Context Switching 이란?
* DeadLock 가 무엇이며, 4가지 조건은?
* DeadLock 해결 하는 방법?

**Comment by Kinaan-Oh** [comment]
1.  데드락(DeadLock)

두 프로세스가 서로 원하는 자원이 상대방에게 할당되어있어서 무한히 대기하는 상태. 해결할 수 없는 환형 대기(Circular Wait) 상태.

![다운로드](https://user-images.githubusercontent.com/81892038/195381534-42969c4a-72d6-41ff-8598-681e85e184d6.jpeg)

2.  발생 조건

- 상호 배제(Mutual Exclusion) : 한 순간에 한 프로세스만이 자원을 사용할 수 있다. 즉 한 프로세스에 의해 점유된 자원을 다른 프로세스들이 접근할 수는 없다.
- 점유 대기(Hold and Wait) : 조건 자원을 기다리는 프로세스가 이미 다른 자원을 할당하고 있다.
- 비선점(No Preemption) : 프로세스에 의해 점유된 자원을 다른 프로세스가 강제적으로 빼앗을 수 없다.
- 환형 대기(Circular Wait) : 프로세스들 간에 닫힌 연결(closed chain)이 존재한다. 즉, 자원 할당 그래프에서 환형이 만들어지는 것이다. 닫힌 연결에서 블록된 프로세스가 자원을 점유하고 있는데, 이 자원을 체인 내부의 다른 프로세스가 원하며 대기하고 있다.

3.  해결 방법

1)  예방 :  데드락 발생 조건 중 하나를 설계 단계에서 배제한다.
- 상호 배제 부정 : 여러 프로세스가 공유 자원 사용.
- 점유 대기 부정 : 프로세스는 자신이 사용할 모든 자원을 한 순간에 요청.
- 비선점 부정 : 자신이 점유한 자원을 일단 반납 후 원래의 자원과 새로 원하는 자원을 함께 요청.
- 환형 대기 부정 : 자원들의 할당 순서를 정해 환형 대기조건 제거.

2)  회피 : 자원을 할당할 때 교착상태가 발생 가능한 상황으로 진행하지 않도록 고려
- 프로세스 시작 거부 : 프로세스가 시작하려 할 때 요구하는 자워 할당이 교착상태 발생의 가능성이 있으면, 프로세스를 시작시키지 않는 방법.
- 자원 할당 거부 : 수행 중인 프로세스가 요구하는 추가적인 자원 할당이 교착상태 발생의 가능성이 있으면, 자원을 할당하지 않는 방법.

3)  발견 : 자원 할당이 가능하면 항상 할당. 단, 주기적으로 시스템에 환형 대기조건이 발생했는지 검사하고 발생하면 해결.

**Comment by gaeunpark924** [comment]
### Context Switching 이란?

- 인터럽트를 발생시켜 CPU에서 실행중인 프로세스를 중단하고 다른 프로세스를 처리하기 위한 과정
- 실행 중인 프로세스의 context를 저장하고, 앞으로 실행 할 프로세스의 context를 복구하는 일
    - Context Saving : 현재 프로세스의 context를 저장하는 작업
    - Context Restoring : context를 프로세스로 복구하는 작업
- Context: 프로세스와 관련된 정보들의 집합

### DeadLock 가 무엇이며, 4가지 조건은?

- 한정된 자원을 여러 프로세스가 사용하고자 할 때 발생하는 상황
- 프로세스가 자원을 얻기 위해 영구적으로 기다리는 상태

< 데드락 발생 조건 > 

- 4가지 조건이 동시에 성립할 때 데드락(교착상태)이 발생함
1. 상호 배제(Mutable Exclusion) : 자원은 한 번에 하나의 프로세스만 사용할 수 있다.
2. 점유 대기(Hold and Wait) : 자원을 최소한 하나 보유하고 다른 프로세스에 할당된 자원을 추가로 점유하기 위해 대기하는 프로세스가 있어야 한다.
3. 비선점(No Preemption) : 다른 프로세스에 할당된 자원은 강제로 빼앗을 수 없다.
4. 순환대기(Circular Wait) : 대기 프로세스의 집합이 순환 형태로 자원을 대기하고 있어야 한다.

### DeadLock 해결 하는 방법?
    
- 예방(Prevention) : 사전에 데드락이 발생하지 않도록 예방하는 방법
- 회피(Avoidance) : 데드락 발생 가능성을 인정하면서도 시스템 상태를 계속 감시하여 데드락을 회피하는 방법
- 탐지(Detection) 및 회복(Recovery) : 데드락 발생을 허용하지만 데드락이 발견되면 복구하는 방법

1. 예방
- 데드락 발생조건 4가지 중에서 하나라도 발생하지 않게 하는 것
- 비현실적이고 자원 낭비가 발생한다.

2. 회피
**은행원 알고리즘(Banker’s Algorithm)**

- 자원의 최대 가능 할당량을 이용해 시뮬레이션을 돌려서 안정 상태인지 판단하는 것
- 프로세스가 자원을 요구하였을 때, 해당 자원을 빌려준다고 가정하고 안전 상태가 계속 유지되는지 검사한다.
- 안정 상태가 유지되면 자원을 할당하고 안정 상태가 유지되지 않으면 자원 할당 요청을 거절한다.

<img src="https://user-images.githubusercontent.com/51811995/195488906-a858f606-51b6-496c-b761-41811ffdc100.png" width=300>


3. 탐지 및 회복
- 탐지
   - RAG(Resource Allocation Graph, 자원 할당 그래프)를 사용한다.
- 회복
  - 교착 상태에 있는 프로세스를 종료하거나 할당된 자원을 해제시킨다

**Comment by dlgosla** [comment]
- Context Switching 이란?
    - 스케쥴러에 의해서 현재 테스크의 정보를 저장한 뒤 잠시 중단하고 다음 진행할 테스크의 정보를 가져와 다른 테스크를 진행하는 과정
    
- DeadLock 가 무엇이며, 4가지 조건은?
    - 서로가 서로의 작업이 끝나기를 기다리며서 작업이 더이상 진행되지 않는 상태이다.
    - 조건
        - 상호배제 - 한번에 한 프로세스만 자원을 사용할 수 있다
        - 비선점 - 다른 프로세스에 할당된 자원을 뺏을 수 없다
        - 순환대기 - 프로세스들이 순환적으로 다음 프로세스를 진행하는데 필요한 자원을 가지고 있어야 한다
        - 점유 대기 - 한 자원을 점유하고 다른 자원을 얻기 위해 대기하는 프로세스가 있어야 한다

- DeadLock 해결 하는 방법?
    - 예방
        - 비선점 부정
            - 우선 순위가 높은 프로세스가 자원을 선점할 수 있도록 한다.
        - 상호 배제 부정
            - 한 자원을 여러 프로세스가 사용할 수 있도록 한다.
        - 순환 대기 부정
            - 한 방향으로만 자원의 요청이 일어나야 한다
        - 점유 대기 부정
            - 프로세스를 진행하는 데 필요한 모든 자원을 한번에 요청
    
    - 회피
        - 은행원 알고리즘
        - 이 자원을 할당했을 때 안정 상태를 만족하면 할당하고, 그렇지 않으면 대기
    
    - 탐지
        - 자원 할당 그래프
    
    - 회복
        - 교착 상태가 일어난 프로세스들을 모두 중지
        - 교착 상태가 풀릴 때 까지 하나씩 중지

**Comment by Mangso** [comment]
# 운영체제

### Q. Context Switching 이란?

---

- `Context` 는 현재 프로세스에 사용되는 자원 혹은 개체들의 상태를 의미를 한다.
- CPU 가 스케줄링에 따라서 프로세스들에게 CPU를 할당해줄 때, 현재 CPU 가 할당된 프로세스의 정보를 저장하고 새로운 Process의 정보를 설ㅈ어후, CPU 를 할당하여 실행되도록 하는 것.
- `기존의 프로세스가 가진 정보를 저장하는 과정`, `실행될 프로세스가 가졌었던 정보를 재할당 하는 과정` 을 진행.
- 인터럽트를 발생시켜 CPU에서 실행중인 프로세스를 중단하고, 다른 프로세스를 처리하기 위한 과정.
- `Context` 는 현재 프로세스에 사용되는 자원 혹은 개체들의 상태를 의미를 한다.
- Context Switch가 발생하는 경우는 멀티태스킹, 인터럽트 핸들링, 사용자 모드와 커널 모드 간의 전환까지, 크게 3가지가 존재한다.

- **`멀티태스킹(Multitasking)`**
    - 실행 가능한 프로세스들이 운영체제의 스케줄러에 의해 조금씩 번갈아가며 수행되는 것을 말한다.
    - 번갈아 가며 프로세스가 CPU를 할당 받는데 이때 Context Switching 한다.
    - 사용자가 체감하기 힘든 속도로 Context Switching되며 프로세스가 처리되기 때문에 동시에 처리되는 것처럼 느껴진다.
- **`인터럽트 핸들링(Interrupt handling)`**
    - 인터럽트란 컴퓨터 시스템에서 예외 상황이 발생했을때 CPU에게 알려 처리할 수 있도록 하는 것을 말한다.
    - 인터럽트가 발생하면 Context Switching한다.
    - I/O request : 입출력 요청
    - time slice expired : CPU 사용시간이 만료
    - fork a child : 자식 프로세스 생성
    - wait for an interrupt : 인터럽트 처리 대기
- **`사용자와 커널 모드 전환(User and kernel mode switching)`**
    - 사용자와 커널 모드 전환은 Context Switch가 필수는 아니지만 운영체제에 따라 발생할수 있다

**Context Switching 과정**

- 현재 작업 대부분 정보는 레지스터에 저장되고 PCB 로 관리됨.
- 현재 실행 하고 있는 Task의 PCB 정보를 저장함. (Process STack, Ready Queue)
- 다음 실행할 Task 의 PCB 정보를 읽어 Register 에 적재하고 CPU가 이전에 진행했던 과정을 연속적으로 수행할 수 있음.

**프로세스 vs 쓰레드 비용 차이**

- Process Context Switiching 비용 > Thread Context Switching 비용
- 왜? Thread 는 Stack 영역을 제외한 모든 메모리를 공유하기 때문에 Context Switching 수행 시 Stack 영역만 변경하면 되기 때문!
- Context Switching하는 동안 CPU는 아무일도 하지않는 시간이 발생하는데 이를 오버헤드(Overhead)라 하고 오버헤드가 잦아지면 성능이 떨어질수 있다.

### Deadlock

---

- 2개 이상 프로세스들이 자원을 점유한 상태에서 서로 다른 프로세스가 점유하고 있는 자원을 요구하며 무한정 기다리는 현상.
- 발생조건
    - **`Mutual exclusion (상호 배제`**) : 한 번에 한 개의 프로세스 만이 공유 자원을 사용할 수 있어야 함.
        - 리소스를 공유해서 사용할 수 없음.
        - 이 리소스는 Critical section, Lock 이런게 될수 있고 메모리, CPU, SSD 등도 될 수 있음.
    - **`Hold & wait(점유와 대기`**) : 최소한 하나의 자원을 점유하고 있으면서 다른 프로세스에 할당되어 사용하고 있는 자원을 추가적을 사용하기 위해서는 대기하는 프로세스가 필요
    - **`No preemtion (비선점 )`** : 다른 프로세스에 할당된 자원은 사용이 끝날 때까지 강제로 빼았을 수 없다.
        - 리소스 반환은 오직 그 리소스를 취득한 프로세스만 할 수 있따.
    - **`Circular wait (원형 대기`**) : 공유 자원과 그 자원을 사용하기 위해 대기하는 프로세스 들이 원형으로 구성되어있어 자신에게 할당된 자원을 점유하면서 앞이나 뒤에 있는 프로세스의 자원을 요구해야 함.
        - 프로세스들이 순환 형태로 서로의 리소스를 기다림

### Deadlock 해결방법

- **데드락 방지** : 4가지 조건 중 하나가 충족되지 않게 시스템을 디자인함.
    1. 리소스 공유하게 하는 것.
        1. 현실적으로 불가능 함. 이유가 있어 critical section을 만들고 lock 을 했는데..
    2. 사용할 리소스들을 모두 획득한 뒤에 시작 하거나 리소스를 전혀 가지지 않은 상태에서만 리소스를 요청하는 방법.
        1. 이 방법 사용하려면, 필요한 자원에 대한 정보를 미리 파악해야 하는데 이 정보를 파악하는데 많은 시간 낭비가 발생하고 드는 비용, 자원에 대한 내용 저장 및 관리가 굉장히 어려워서 문제점이 많음.
    3. 다른 프로세스에 할당된 자원을 가져와서 사용 가능하게 함.
        1. 이거 또한 동기화에 대한 의미가 깨져버리는 방식이어서 실질적으로 불가능 함.
    4. 선형 대기로 만들어서, 필요한 자원들을 순차적으로 획득한 후 실행하는 방법
        1. 그나마 주로 사용되는 예방 기법, 중첩되어 있는 공유자원 사이에 요청 순서를 임의적으로 정해줌으로써 여러 개의 프로세스가 순환형 대기에 머물러 있게 되는 상황을 방지하는 기법이다.
- **데드락 회피**
    - 교착상태가 발생할 가능성을 0으로 만드는 게 아닌, 발생하더라도 피해가는 기법
    - 가능성 전혀 없을 때만, 자원을 할당하여 발생 방지
    - 대표적으로 은행원 알고리즘
        - 최소한 하나의 프로세스에게 할당해줄 만큼 자원은 항상 CPU가 보유하고 있어야 한다 라는 개념.
        - 특정 자원을 프로세스
    - 사용 거의 X
- **데드락 회복**
    - 발생한 이후 회복하는 방식, 프로세스를 모두 죽이거나, 하니씩 죽이는 방법 존재
    
    - 사용자가 직접 처리
    - 시스템에 의해 처리
        - 프로세스 중지는 한 개 이상의 프로세스를 중지시킴으로써 교착상태를 회복하는 기법이다.
        - 모든 프로세스 죽이거나, 한 프로세스씩 중지 시키는 방법
        - 모든 프로세스 죽이는 방법 : 확실하게 가능, but 비용 많이 듬.
            - 왜? 오랫동안 연산을 했을 경우, 결과 다 버리고 다시 처음부터 진행 해야 하기 때문.
        
        하나씩 중지시키는 방법 : 모든 프로세스 탐색하면서, 교착상태 알고리즘 호출하여 여부를 확인해야해서 오버헤드 크다는 단점
        
    - 자원 선점
        - 프로세스들로 부터 자원 뺏어서 교착상태가 해결될때까지 프로세스에게 할당해 주는 방식
            - 선점 프로세스 선택
            - 복귀 (Rollback) : 완전히 중지시킨 후 재 시작 해야함
            - 기아 (Starvation)
- **데드락 무시**
    - 데드락에 대해 아무일도 하지 않음
    - Window 포함 대부분의 OS 가 채택하는 방법
    - 운영체제가 관여안하면 사용자가 알아서 프로세스 죽임
    - 빈번히 발생하는 이벤트가 아니라서 1,2,3 이 비효율적.

**Comment by jumi-shim** [comment]
### Context Switching

CPU가 현재 수행하고 있는 작업(Process, Thread)의 상태를 저장하고 다음에 진행할 작업의 상태 Register 값들에 대한 정보(Context)를 읽어 새로운 작업의 Context 정보로 교체하는 과정.

CPU를 한 프로세스에서 다른 프로세스로 넘겨주는 과정

Context : CPU가 다루는 작업에 대한 정보. 대부분의 정보는 Register에 저장되고 PCB로 관리됨.

CPU가 이전의 프로세스 상태를 PCB에 보관하고 또 다른 프로세스의 정보를 PCB에서 읽어서 레지스터에 적재하는 과정.

- 언제 발생?
    
    Interrupt가 발생하거나 실행 중인 CPU 사용 시간을 모두 소모하거나 입출력을 위해 대기해야 하는 경우.
    
    프로세스가 Ready → Running, Running → Ready, Running → Block 처럼 상태 변경 시에 발생. 그러므로 Context Switching을 하는 주체는 CPU 스케줄러.
    
    ### Context Switching Overhead

Context Switching이 발생하게 되면 아래와 같은 과정이 필요.

- Cache 초기화
- Memory Mapping 초기화
- 메모리 접근을 위해서 Kernel은 항상 실행되어야 함.

이 과정에서 소요되는 시간을 Cost. Cost는 낭비되는 시간이라고 생각할 수 있음. 이렇게 어떤 과정을 할 때 소모되는 Cost들을 Overhead라고 함. → 어떤 작업을 할 때 Overhead가 높다는 것은 그 과정을 수행하기 위해 필요한 다른 작업들의 Cost가 높다는 것.

Context Switching은 Overhead가 높은 작업이고 잦은 Context Switching은 성능 저하를 가져옴.

Context Switching이 높은 Overhead를 갖음에도 수행하는 이유는 그것을 감안해도 더 이득이기 때문.


### Deadlock 교착상태
    
    일련의 프로세스, 스레드들이 서로 가진 자원을 기다리며 block된 상태
    
    - 자원
        
        하드웨어, 소프트웨어 등을 포함하는 개념. I/O device, CPU cycle, memory space, semaphore 등
        
        프로세스가 자원을 사용하는 절차. Request, Allocate, Use, Release.
        
    - deadlock의 발생 4가지 필수 조건
        - mutual exclusion 상호 배제
            
            매 순간 하나의 프로세스만이 자원을 사용할 수 있음.
            
        - no preemption 비선점
            
            프로세스는 자원을 스스로 내어놓을 뿐 강제로 빼앗기지 않음.
            
        - hold and wait 보유 대기
            
            자원을 가진 프로세스가 다른 자원을 기다릴 때 보유 자원을 놓지 않고 계속 가지고 있음.
            
        - circular wait 순환대기
            
            자원을 기다리는 프로세스간에 사이클이 형성되어야 함.
            
    - deadlock 처리 방법
        - deadlock prevention 예방
            
            자원 할당 시 deadlock의 4가지 필요 요건 중 어느 하나가 만족되지 않도록 하는 것.
            
            이용률 저하, 성능 저하, starvation 문제.
            
            - mutual exclusion
                
                공유해서는 안되는 자원의 경우 반드시 성립해야 함.
                
            - no preemption
                
                어떤 자원을 점유하고 있는 프로세스가 다른 자원을 요청했지만 해당 자원을 당장 프로세스에 할당할 수 없는 경우 원래 점유하고 있던 자원이 선점될 수 있게 해야 함.
                
                모든 필요한 자원을 얻을 수 있을 때 그 프로세스는 다시 시작됨.
                
                state를 쉽게 save하고 restore할 수 있는 자원에서 주로 사용 (CPU, memory)
                
            - **hold** and wait
                
                프로세스가 자원을 요청할 때 다른 어떤 자원도 가지고 있지 않아야 함.
                
                1. 프로세스 시작 시 모든 필요한 자원을 할당받게 하는 방법
                2. 자원이 필요할 경우 보유 자원을 모두 놓고 다시 요청
            - circular wait
                
                모든 자원 유형에 할당 순서를 정하여 정해진 순서대로 자원 할당.
                
        - deadlock avoidance 회피
            
            자원 요청에 대한 부가적인 정보를 이용해서 deadlock의 가능성(동적으로 조사함)이 없는 경우에만 자원 할당.
            
            시스템 state가 원래 state로 돌아올 수 있는 경우에만 자원 할당.
            
            가장 단순하고 일반적인 모델은 프로세스들이 필요로 하는 각 자원별 최대 사용량을 미리 선언하도록 하는 방법.
            
            - 자원 할당 그래프 알고리즘
                
                요청간선, 할당 간선, 예약 간선 이용. 예약 간선은 프로세스가 미래에 해당 자원을 요청할 것을 의미. 프로세스 실행 전 예약 간선을 자원 할당 그래프에 명시하여 교착 상태 예측.
                
            - 은행원 알고리즘 Banker’s Algorithm
                
                프로세스의 자원 요청을 허가했을 때 시스템이 안전 상태에 머무른다면 요청을 들어주고 그렇지 않다면 프로세스를 대기시킴.
                
        - deadlock detection and recovery
            
            deadlock 발생은 허용하되 그에 대한 detection 루틴을 두어 deadlock 발견시 recover
            
            - dectection
                
                자원 유형이 한 개씩 있는 경우 : 대기 그래프가 사이클을 포함할 경우 교착상태 존재.
                
                자원 유형이 여러 개 있는 경우 : 교착상태 발생 빈도와 교착상태 발생 시 몇 개의 프로세스가 연루되는지에 따라 교착 탐지 알고리즘 실행.
                
            - recovery
                - Process termination
                    
                    교착 상태의 프로세스들 모두 중지 → 연산 내용 폐기되므로 비용 큼
                    
                    교착 상태에서 빠져나올 때까지 한 프로세스씩 중지 → 중지될 때마다 교착 상태 탐지 알고리즘 호출해야 하므로 오버헤드.
                    
                - resource preemption
                    
                    희생자 선택. 롤백 상태 선택. 기아상태 발생하지 않도록.
                    
        - deadlock ignorance
            
            deadlock을 시스템이 책임지지 않음.
            
            UNIX를 포함한 대부분의 OS가 채택
