### ISSUE TITLE
Stack & Queue

### ISSUE THREAD

**Issue by gaeunpark924** [Tech-Interview-A/Tech-Interview-Quetions#7]
- Stack과 Queue의 차이점?
- Stack 두 개를 이용하여 Queue를 구현해 보세요

**Comment by Kinaan-Oh** [comment]
1.  Stack

 스택은 톱(top)이라고 하는 한쪽 끝에서 모든 삽입(push)과 삭제(pop)이 일어나는 순서 리스트. 후입 선출(LIFO: Last-In-First-Out) 리스트라고도 한다.

Stack 추상 데이터 타입
```
template<class T>
class Stack {
	public:
		bool IsEmpty() const; // 스택의 원소 수가 0이면 true, 아니면 false를 반환
		T& Top() const; // 스택의 톱 원소를 반환
		void Push(const T& item); // 스택의 톱에 item을 삽입
		void Pop(); // 스택의 톱 원소를 삭제
}
```
 
3.  Queue

 큐는 한쪽 끝에서 삽입이 일어나고 그 반대쪽 끝에서 삭제가 일어나는 순서 리스트. 원소가 삽입되는 끝을 리어(rear), 원소가 삭제되는 끝을 프런트(front)라 한다. 선입 선출(FIFO: First-In-First_Out) 리스트라고도 한다.

 

Queue 추상 데이터 타입
```
template<class T>
class Queue {
	public:
		bool IsEmpty() const; // 큐의 원소 수가 0이면 true, 아니면 false를 반환
		T& Front() const; // 큐의 앞에 있는 원소를 반환
		T& Rear() const; // 큐의 뒤에 있는 원소를 반환
		void Push(const T& item); // 큐의 뒤에 item을 삽입
		void Pop(); // 큐의 얖 원소를 삭제
}
```
 
 Stack, Queue 모두 배열, 연결 리스트로 구현할 수 있다. 배열은 크기가 고정인 문제(빈 공간이 없는 경우 더 큰 배열을 할당하고 복사하는 오버헤드)이 있지만, 연결 리스트는 이 문제를 해결한다. 다만, 연결 리스트는 링크를 추가로 가지므로 배열보다 많은 메모리가 필요하다.

![다운로드](https://user-images.githubusercontent.com/81892038/195627870-0a7aad86-7421-4210-b462-a9cd6b14e090.jpeg)
연결 리스트로 구현한 큐

![다운로드 (1)](https://user-images.githubusercontent.com/81892038/195627899-4244c386-3d56-4378-9558-3029dd41091c.jpeg)
연결리스트로 구현한 스택
 
4.  Stack으로 Queue를 구현하기
 
Stack 2개로 구현한다.(Push: O(1), Pop: O(n))

```
class MyQueue {
private:
    stack<int>  stk1;
    stack<int>  stk2;
    
public:
    MyQueue() {
    }
    
    void push(int x) {
        while(!stk1.empty()) {
            stk2.push(stk1.top());
            stk1.pop();
        }
        
        stk1.push(x);
        
        while(!stk2.empty()) {
            stk1.push(stk2.top());
            stk2.pop();
        }
    }
    
    int pop() {
        int ret = peek();
        stk1.pop();
        return ret;
    }
    
    int peek() {
        return stk1.top();
    }
    
    bool empty() {
        return stk1.empty();
    }
};
```
 
https://leetcode.com/problems/implement-queue-using-stacks/
 
5.  Queue으로 Stack 구현하기

기본 풀이는 Queue 2개로 구현한다.(Push: O(1), Pop: O(n))
Queue 1개로도 구현할 수 있다.

```
class MyStack {
private:
    queue<int>  que;
public:
    MyStack() {
    }
    
    void push(int x) {
        que.push(x);
        
        for(int i=0;i<que.size()-1;i++) {
            que.push(que.front());
            que.pop();
        }
    }
    
    int pop() {
        int ret = que.front();
        que.pop();
        return ret;
    }
    
    int top() {
        return que.front();
    }
    
    bool empty() {
        return que.empty();
    }
};
```
 
https://leetcode.com/problems/implement-stack-using-queues/

**Comment by jumi-shim** [comment]
- Stack
    
    선형 자료구조. LIFO(Last In Frist Out) 나중에 들어간 원소가 먼저 나옴. 
    
    - 언제 사용?
        
        함수의 콜 스택, dfs, 뒤로가기, 재귀, 실행취소
        
- Queue
    
    선형 자료구조. FIFO(First In First Out) 먼저 들어간 원소가 먼저 나옴.
    
    - 언제 사용?
        
        버퍼, bfs, cpu 스케줄링
        
    - 원형 큐
        
        논리적으로 배열의 처음과 끝이 연결되어 있는 것으로 간주.
        
        메모리 공간을 잘 활용하지만 배열로 구현되어 있기 때문에 큐의 크기가 제한. → 연결리스트 큐로 개선

**Comment by dlgosla** [comment]
스택

- lifo
- 어떤 경우? - dfs, 후위표기법
- 단순하고 빠른 성능을 위해 스택을 사용하므로 보통 배열로 구현함
- 배열로 구현
    - 속도가 빠름
    - 크기가 고정돼 있어 데이터가 많으면 새로운 배열에 복사 해야해서 시간이 오래걸림
    
- 링크드 리스트로 구현
    - 동적으로 크기를 정할 수 있어 크기를 몰라도 됨
    - 삽입, 삭제 시 메모리 동적 할당 때문에 좀 느림
    

큐

- fifo
- 어떤 경우? - bfs, print출력
- 보통 링크드 리스트로 구현
- 배열로 구현
    - 크기가 고정돼 있어 데이터가 많으면 새로운 배열에 복사 해야해서 시간이 오래걸림
    - 구현 복잡 (큐의 앞쪽을 활용 못해서 순환 큐 만들어야 됨)

- 링크드 리스트로 구현
    - 구현 쉬움
    - 메모리 오버헤드

- Stack 두 개를 이용하여 Queue를 구현해 보세요
    - push할 때는 1번 스택에 한다.
    - pop할 때 2번 스택이 비어있으면 1번 스택의 모든 요소를 pop해서 순서대로 넣고 하나를 pop한다.
    - 2번 스택이 비지 않았으면 2번 스택에서 pop한다.

- 큐 두개로 스택
    - enqueue할 때는 1번 큐에 한다.
    - dequeue할 때는 1번 큐에서 원소가 하나 남을 때 까지 dequeue해서 2번 큐에 넣고 1번 큐에 남은 원소를 result로 리턴한다. 그리고 2번 큐의 모든 원소를 dequeue해서 다시 1번 큐에 넣는다.

**Comment by dlgosla** [comment]
혹시 스터디 진행 중이신가요..? 제가 알고 있는 주소가 잘못된 건지 안들어가지는데 카톡이 안돼서 확인을 할 수가 없네요..

**Comment by jumi-shim** [comment]
https://meet.google.com/wjv-czoe-mpj  현식님이 노션에 새로 주소 올려주셨어요!

**Comment by gaeunpark924** [comment]
> stack 과 queue의 차이점?

### Stack
- 나중에 들어간 데이터가 먼저 나오는 **LIFO**, **Last-In First-Out** 자료구조
- 가장 최근에 삽입된 자료 위치인 top을 통해서만 접근 가능
- 기본 연산
    - push : 데이터를 넣는 것
    - pop : 데이터를 꺼내는 것
    - peek : 꺼낼 데이터를 확인하는 것
- 구현 방법
    - 배열, 연결리스트
- 언제 사용? : 함수의 콜스택, 문자열 역순 출력, 연산자 후위표기법

### Queue
- 먼저 들어간 데이터가 먼저 나오는 **FIFO**, **First-In First-Out** 자료구조
- 스택과 다르게 양쪽 끝에서 데이터의 삽입 삭제가 이루어진다.
    - front : 데이터가 제거되는 곳
    - rear : 데이터가 삽입되는 곳
- 기본 연산
    - enqueue : 데이터를 넣는 것
    - dequeue : 데이터를 꺼내는 것
- 구현 방법
    - 배열과 연결리스트로 구현할 수 있다.
    - 배열
        - 장점 : 포인터를 저장하지 않아도 되기 때문에 메모리가 적게 든다
        - 단점 : 크기가 제한적이다
        - 원형 큐를 배열로 구현함
     - 연결 리스트(원형 큐의 단점 개선함) → 크기에 제한이 없어 연결리스트가 좀 더 권장된다.
        - 장점 : **크기에 제한이 없음**, 스택도 연결리스트로 구현 가능
        - 단점 : 포인터를 하나씩 더 들고 있어서 **메모리가 조금 더 든다**
- 언제 사용? : 버퍼, 마구 입력된 것을 처리하지 못하고 있는 상황, BFS

**Comment by Mangso** [comment]
### **Stack**

- 스택(Stack)의 개념
    - 한 쪽 끝에서만 자료를 넣고 뺄 수 있는 LIFO(Last In First Out) 형식의 자료 구조
- 스택(Stack)의 연산
    - 스택(Stack)는 LIFO(Last In First Out) 를 따른다. 즉, 가장 최근에 스택에 추가한 항목이 가장 먼저 제거될 항목이다.
        - pop(): 스택에서 가장 위에 있는 항목을 제거한다.
        - push(item): item 하나를 스택의 가장 윗 부분에 추가한다.
        - peek(): 스택의 가장 위에 있는 항목을 반환한다.
        - isEmpty(): 스택이 비어 있을 때에 true를 반환한다.
- 스택(Stack)의 사용 사례
    - 재귀 알고리즘을 사용하는 경우 스택이 유용하다.
        - 재귀 알고리즘
            - 재귀적으로 함수를 호출해야 하는 경우에 임시 데이터를 스택에 넣어준다.
            - 재귀함수를 빠져 나와 퇴각 검색(backtrack)을 할 때는 스택에 넣어 두었던 임시 데이터를 빼 줘야 한다.
            - 스택은 이런 일련의 행위를 직관적으로 가능하게 해 준다.
            - 또한 스택은 재귀 알고리즘을 반복적 형태(iterative)를 통해서 구현할 수 있게 해준다.
        - 웹 브라우저 방문기록 (뒤로가기)
        - 실행 취소 (undo)
        - 역순 문자열 만들기
        - 수식의 괄호 검사 (연산자 우선순위 표현을 위한 괄호 검사)
            - Ex) 올바른 괄호 문자열(VPS, Valid Parenthesis String) 판단하기
        - 후위 표기법 계산

> ⏫Top ↩️Back ℹ️Home
> 
> - [https://gmlwjd9405.github.io/2018/08/03/data-structure-stack.html](https://gmlwjd9405.github.io/2018/08/03/data-structure-stack.html)

스택 2개로 큐 구현.

- Stack1, Stack2 를 만듬
- Stack1에 다 push 때림
- 그 다음 pop 하여 Stack2 에 push 함.
- Stack2에서 pop 하면 됨.
- 

큐 2개로 스택 구현

1. 메인 큐에 값을 넣는다.(put) ex) 1→ 2→ 3 → 4
2. 메인 큐에 1개의 원소가 남을 때까지 get 한 값을 임시 큐에 put 한다.
3. 마지막 남은 원소는 result 변수에 저장한다.
4. 임시 큐에 있는 원소들을 메인 큐로 모두 이동시킨다. (get → put)
5. result 값을 리턴한다.

### **Queue**

- 큐(Queue)의 개념
    - 컴퓨터의 기본적인 자료 구조의 한가지로, 먼저 집어 넣은 데이터가 먼저 나오는 FIFO(First In First Out)구조로 저장하는 형식
- 큐(Queue)의 연산
    - 큐(Queue)는 FIFO(First-In-First-Out) 를 따른다.
        - add(item): item을 리스트의 끝부분에 추가한다.
        - remove(): 리스트의 첫 번째 항목을 제거한다.
        - peek(): 큐에서 가장 위에 있는 항목을 반환한다.
        - isEmpty(): 큐가 비어 있을 때에 true를 반환한다.
- 큐(Queue)의 사용 사례
    - 데이터가 입력된 시간 순서대로 처리해야 할 필요가 있는 상황에 이용한다.
        - 너비 우선 탐색(BFS, Breadth-First Search) 구현
            - 처리해야 할 노드의 리스트를 저장하는 용도로 큐(Queue)를 사용한다.
            - 노드를 하나 처리할 때마다 해당 노드와 인접한 노드들을 큐에 다시 저장한다.
            - 노드를 접근한 순서대로 처리할 수 있다.
        - 캐시(Cache) 구현
        - 우선순위가 같은 작업 예약 (인쇄 대기열)
        - 선입선출이 필요한 대기열 (티켓 카운터)
        - 콜센터 고객 대기시간
        - 프린터의 출력 처리
        - 윈도우 시스템의 메시지 처리기
        - 프로세스 관리
