### ISSUE TITLE
웹 동작 방식

### ISSUE THREAD

**Issue by gaeunpark924** [Tech-Interview-A/Tech-Interview-Quetions#8]
- 주소창에 naver.com을 치면 일어나는 일?

**Comment by Kinaan-Oh** [comment]
학생 밥(Bob)이 학교의 이더넷 스위치에 랩톤을 연결하고 웹 페이지(www.naver.com)를 다운로드 하는 과정은 다음과 같다.

1.  Client IP 획득 (DHCP)

- 밥의 랩톱의 운영체제는 DHCP 요청 메시지를 만들어서 DHCP 서버 포트번호를 목적지로 하는 UDP 세그먼트에 넣는다. 이 UDP 세그먼트는 브로드캐스트 IP 목적지 주소(255.255.255.255)와 출발지 IP 주소(0.0.0.0)를 갖는 IP 데이터그램에 들어간다.
- DHCP 요청 메시지를 포함한 IP 데이터그램은 이더넷 프레임에 들어간다. 브로드캐스트 될 수 있도록 목적지 MAC 주소는 FF:FF:FF:FF:FF:FF로 설정된다. 출발지 MAC 주소는 밥 랩톱의 MAC 주소인 00:16:D3:23:68:8A가 된다.
- 밥의 랩톱은 DHCP ACK를 포함하는 이더넷 프레임을 수신한 후 UDP 시그먼트를 추출하며, UDP 세그먼트로부터 DHCP ACK 메시지를 추출한다. 밥은 자신의 IP 주소와 DNS 서버의 IP 주소를 기록한다.

2.  Server IP 획득 (DNS)

- DNS 질의 메시지를 게이트 웨이 라우터로 전송하기 위해 게이트웨이 라우터 MAC 주소가 필요하다. 게이트 웨어 IP 주소를 목적지 주소로 하는 ARP 질의 메시지를 브로트캐스트 목적지 주소 FF:FF:FF:FF:FF:FF를 갖는 이더넷 프레임에 포함하여 질의한다.
- 밥 랩톱 운영체제는 ARP 응답 메시지를 통해 게이트웨이 라우터 MAC 주소를 획득한다.
- 밥 랩톱의 운영체제는 DNS 질의 메시지를 생성한다. DNS 질의 메시지는 DNS 서버포트번호를 목적지 주소로 하는 UDP 세그먼트에 들어간다. UDP 세그먼트는 Client IP 주소를 출발지로 하고 DNS IP 주소를 목적지 주소로 하는 데이터 그램에 들어간다. 데이터 그램은 게이트웨이 라우터 MAC 주소를 목적지 주소로 하는 이더넷 프레임을 전송한다.
- 밥의 랩톱은 DNS 응답 메시지로부터 www.naver.com의 IP 주소를 획득한다.

3.  TCP 연결 (3-way handshake) & HTTP 메시지 교환

- 밥의 랩톱은 목적지 포트 80(HTTP 용)을 갖는 TCP SYN 세그먼트를 생성하고, www.naver.com의 IP 주소를 목적지 주소로 하는 데이터그램에 넣고, 데이터 그램을 목적지 MAC 주소가 게이트웨이 라우터 주소인 이더넷 프레임을 생성하여 전송한다.
- 밥의 랩톱이 TCP SYNACK 세그먼트를 수신하면, HTTP GET 메시지를 포함한 TCP 세그먼트를 이더넷 프레임에 포함하여 전송한다.
- 밥의 랩톤은 수신한 HTTP 응답 메시지의 바디로부터 웹 페이지에 대한 html을 추출한 후 웹 페이지를 출력한다.

4.  TCP 연결 해제 (4-way handshake)

- 밥의 랩톱은 FIN 세그먼트(FIN 비트 1)를 생성하고, www.naver.com의 IP 주소를 목적지 주소로 하는 데이터그램에 넣고, 데이터 그램을 목적지 MAC 주소가 게이트웨이 라우터 주소인 이더넷 프레임을 생성하여 전송한다.
- 밥의 랩톱은  ACK 세그먼트를 수신한다.
- 서버는 FIN 세그먼트(FIN 비트 1)를 밥의 랩톱으로 전송한다.
- 밥의 랩톱은 ACK 세그먼트를 서버로 전송한다.

**Comment by jumi-shim** [comment]
1. 웹 사이트 url을 브라우저 주소창에 침
2. 브라우저는 캐싱된 DNS 기록을 통해 url과 대응되는 ip 주소가 있는지 확인
    - 브라우저 캐시, OS 캐시, 라우터 캐시, ISP 캐시 확인
        - ISP (Internet Service Provider)
            
            DNS 서버 가지고 있음.
            
            인터넷 서비스 사용자, 인터넷 서비스를 제공하는 주체. kt, skt , lg u+
            
            [https://code-designer.tistory.com/m/132](https://code-designer.tistory.com/m/132)
            
3. 요청한 url이 캐시에 없으면 ISP의 DNS 서버가 url을 호스팅하고 있는 서버의 ip 주소를 찾기 위해 DNS쿼리 날림.
4. 브라우저가 ip 주소를 받으면 서버와 tcp 연결을 함 (3-way)
5. tcp 연결이 완료되면 브라우저가 웹 서버에 http 요청을 함.
6. 서버가 요청을 처리하고 response 생성하여 http response 보냄.
7. 브라우저가 html content 보여줌.

**Comment by dlgosla** [comment]
1. dns 서버에서 네이버에 해당하는 ip 주소 얻음
2. 해당 ip주소에 해당하는 페이지를 요청하기 위해 tcp를 이용해 http 요청을 보냄
3. 네이버 서버에서 요청을 받음
4. 네이버 서버에서 body에 html 문서를 담아서 http 요청을 보냄
5. 브라우저가 html 문서를 파싱하고 dom 트리를 만들어서 페이지를 랜더링

**Comment by gaeunpark924** [comment]
HTTP, TCP, IP, Ethernet을 사용한다고 가정

**클라이언트**

1. 응용 계층(Application Layer)
    - 사용자가 브라우저에 URL을 입력하고 **HTTP 프로토콜**을 사용해 HTTP 요청/응답 메시지를 받는다.
    - 응용계층에서 사용되는 프로토콜 : HTTP, SMTP, SSH, FTP
2. 전송 계층(Transport Layer) 
    - TCP헤더에 PC **포트 번호**와 HTTP 80번 포트를 넣고 응용 계층의 데이터를 추가하여 세그먼트을 생성한다.
    - 데이터를 주고 받기 전에 3-way handshake로 연결을 설정하고 마지막에 4-way handshake로 연결을 해제한다.
    - 전송 계층에서 사용되는 프로토콜 : TCP, UDP
3. 인터넷 계층(Internet Layer)
    - IP헤더에 PC의 **IP주소**와 서버의 IP주소를 넣고 전송 계층의 세그먼트를 추가하여 IP패킷을 생성한다.
    - 인터넷 계층에서 사용되는 프로토콜 : IP, ARP
4. 네트워크 계층(Network Access Layer) 
    - 다른 계층과 마찬가지로 소스와 목적지의 MAC주소를 헤더에 넣고 프레임을 생성한다.
    - 물리적으로 연결된 **라우터**를 통해 데이터를 전달한다.

**서버**

1. 네트워크 계층
    - 라우터로부터 받은 프레임을 디캡슐화하여 목적지 IP를 확인한다.
2. 인터넷 계층
    - 네트워크 계층에서 받은 IP 패킷을 디캡슐화하여 80번 포트를 확인한다.
3. 전송 계층
    - 인터넷 계층에서 받은 세그먼트를 디캡슐화하여 데이터를 확인한다.
4. 응용 계층
    - 데이터에서 HTTP Request 정보를 알게 된다.
