### ISSUE TITLE
Semaphore & Mutex

### ISSUE THREAD

**Issue by gaeunpark924** [Tech-Interview-A/Tech-Interview-Quetions#9]
- 세마포어(Semaphore)와 뮤텍스(Mutex)의 차이

**Comment by Kinaan-Oh** [comment]
1.  뮤텍스(Mutex)

- 여러 스레드를 사용하는 환경에서 자원에 대한 접근을 강제하기 위한 동기화 메커니즘.
- Boolean 타입의 Lock 변수 사용.
- 공유자원을 사용중인 스레드가 있을 때, 다른 스레드가 공유자원에 접근한다면 Blocking 후 대기 큐로 보낸다.
- Lock을 건 스레드만 Lock을 해제할 수 있다.

2.  세마포어(Semaphore)

- 세마포어 변수를 통해 wait, signal을 관리. 세마포어 변수는 0 이상의 정수형 변수를 갖는다.
wait : 세마포어 값을 감소. 만일 값이 음수가 되면 wait를 호출한 프로세스는 블록됨. 음수가 아니면 프로세스는 계속 수행.
signal : 세마포어 값을 증가. 만일 값이 양수가 아니면 wait 호출하여 블록된 프로세스를 깨움.
- 계수 세마포어로 사용할 수 있으며, 접근 가능한 공유자원의 수가 1개일 때는 이진 세마포어로 뮤텍스처럼 사용할 수 있다.
- Lock을 걸지 않은 스레드도 Signal을 보내 Lock을 해제할 수 있다.

**Comment by jumi-shim** [comment]
스레드 간의 자원 공유는 전역 변수(데이터 세그먼트)를 이용하게 됨. 이를 이용하는 코드는 임계구역 Critaical Section이라 하는데 공유하는 전역 변수를 여러 스레드가 함께 사용하려면 충돌하는 문제가 발생하므로 병행 처리를 위한 동기화를 통하여 문제를 해결해야 함.

- Semaphore
    
    현재 공유자원에 접근할 수 있는 스레드/프로세스의 수를 나타내는 값을 두어 상호배제를 달성하는 기법.
    
    리소스의 상태를 나타내는 카운터. 세마포어는 P와 V라는 동작에 의해 접근할 수 있는데 이는 현재 사용 가능한 자원인 S에 따라 동작.
    
    Signaling 메커니즘으로 락을 걸지 않은 스레드도 signal을 사용해 락을 해제할 수 있음.
    
    - P Operation : 임계 구역에 들어가기 전에 수행. 보호되는 자원이 사용 가능할 때까지 wait/sleep
        
        프로세스 진입 여부를 자원의 개수 S를 통해 결정
        
    - V Operation : 임계 구역에서 나올 때 수행
        
        자원 반납 알림, 대기 중인 프로세스를 깨우는 신호
        
    - 방식
        - busy-wait (= spin lock)
        - Block / Wakeup Immplementation (= sleep lock)
            - block
                
                커널은 block을 호출한 프로세스를 suspend시킴. 이 프로세스의 PCB를 semaphore에 대한 wait queue에 넣음.
                
            - wakeup(P)
                
                block된 프로세스 P를 wakeup시킴. 이 프로세스의 PCB를 ready queue로 옮김.
                
    - busy-wait vs block/wakeup
        
        Critical section의 길이가 긴 경우 Block/Wakeup이 적당
        
        Critical section의 길이가 매우 짧은 경우 Block/Wakeup 오버헤드가 busy-wait 오버헤드보가 더 커질 수 있음.
        
        일반적으로는 Block/Wakeup 방식이 더 좋음.
        
- Mutex
    
    임계 구역을 가진 스레드들의 실행시간이 겹치지 않고 단독으로 실행되게 하는 기술. 뮤텍스는 상태가 0, 1로 이진 세마포어로 부르기도 함.
    
    임계 영역에 들어갈 때 lock을 걸어 다른 프로세스 스레드가 접근하지 못하도록하고 임계 영역에서 나와 unlock.
    
    - lock : 현재 임계 구역에 들어갈 권한을 얻어옴. 만일 다른 프로세스/스레드가 임계구역을 수행 중이라면 종료할 때까지 대기(entry section)
    - unlock : 현재의 임계 구역을 모두 사용했음을 알림. 대기중인 다른 프로세스/스레드가 임계구역에 진입할 수 있음(exit section)
    
    - 데커(Dekker) 알고리즘
        
        flag와 turn 변수를 통해 임계 구역에 들어갈 프로세스/스레드를 결정하는 방식
        
    - 피터슨(Peterson) 알고리즘
        
        데커와 유사하지만 상대방 프로세스/스레드에게 진입 기회를 양보하는 것에 차이가 있음.
        
    - 제과점(Bakery) 알고리즘
        
        여러 프로세스/스레드에 대한 처리가 가능한 알고리즘. 가장 작은 수의 번호표를 가지고 있는 프로세스가 임계 구역에 진입.

**Comment by dlgosla** [comment]
세마포어

- 임계구역에 한번에 특정 개수 만큼의 프로세스/스레드가 접근할 수 있음
- 락을 얻지 않은 다른 프로세스가 세마포어를 해제할 수 있음
- 비지웨잇
    - while을
    - 짧을경우
    
- 블록 앤 웨이크
    - 큐를 이용해서 작업하던 프로세스가 완료되면 웨잇 큐에 있는 프로세스 하나 깨워서 공유자원에 접근할 수 있게
    - 임계 구역이 긴 경우

뮤텍스

- 임계구역에 한번에 하나의 프로세스/스레드만 접근할 수 있음
- 락을 얻은 프로세스만이 락을 해제할 수 있음

**Comment by gaeunpark924** [comment]
> **세마포어와 뮤텍스의 차이**
> 
1. 뮤켁스는 동기화 대상이 하나일 때이고 세마포어는 두 개 이상일 때 사용한다. 뮤텍스는 상태가 0 또는 1인 Binary Semaphore(이진 세마포어)라고 부르기도 한다.
2. 뮤텍스는 자원을 소유하고 있는 쓰레드만이 임계영역을 나갈 때 Lock을 해제할 수 있고 세마포어는 Lock을 걸지 않은 쓰레드도 락을 해제할 수 있다.

**Comment by Mangso** [comment]
### **세마포어**

운영체제에서 공유 자원에 대한 접속을 제어하기 위해 사용되는 신호 공유자원에 접근할 수 있는 최대 허용치만큼만 동시에 사용자 접근 가능 스레드들은 리소스 접근 요청을 할 수 있고, 세마포어는 카운트가 하나씩 줄어들게 되며 리소스가 모두 사용중인 경우(카운트=0) 다음 작업은 대기를 하게 된다

### **뮤텍스**

상호배제, 제어되는 섹션에 하나의 스레드만 허용하기 때문에, 해당 섹션에 접근하려는 다른 스레드들을 강제적으로 막음으로써 첫번재 스레드가 해당 섹션을 빠져나올 때까지 기다리는 것 (대기열(큐) 구조라고 생각하면 됨)

### **차이점**

- 세마포어는 뮤텍스가 될 수 있지만, 뮤텍스는 세마포어가 될 수 없음
- 세마포어는 소유 불가능하지만, 뮤택스는 소유가 가능함
- 동기화의 개수가 다름
